apiVersion: v2
name: msa-chart
description: chart for deploying all services in the Spring Cloud MSA
type: application
version: 1.0.0
appVersion: 1.0.0

# 바깥쪽 차트가 의존하고 있는 내부 차트의 경로를 지정해주는 설정
# 바깥쪽 차트 (msa-chart)를 install 하면, 의존관계가 있는 모든 내부 차트들이 install 이 진행됨
dependencies:
  - name: config-service
    version: 1.0.0
    repository: file://charts/config-service      # 8888
  - name: user-service
    version: 1.0.0
    repository: file://charts/user-service     # 8081
  - name: order-service
    version: 1.0.0
    repository: file://charts/ordering-service   # 8083
  - name: course-service
    version: 1.0.0
    repository: file://charts/course-service   # 8082
  - name: gateway-service
    version: 1.0.0
    repository: file://charts/gateway-service   # 8000
  - name: post-service
    version: 1.0.0
    repository: file://charts/post-service    # 8084
  - name: eval-service
    version: 1.0.0
    repository: file://charts/eval-service    # 8085
